apiVersion: apps/v1
kind: "Deployment"
metadata:
  name: "fr-collector2-deployment"
  labels:
    app: "fr-collector2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "fr-collector2"
  template:
    metadata:
      labels:
        app: "fr-collector2"
    spec:
#      initContainers:
#        - name: dial-rabbitmq
#          image: busybox:glibc
#          command: ["sh","-c","until nc -z -w 5 $RABBITMQ_SERVICE_HOST $RABBITMQ_PORT; do echo waiting; sleep 2; done;"]
#          command: ["sh","-c","nc -vz -w 5 $RABBITMQ_SERVICE_HOST $RABBITMQ_PORT"]
#          command: ["bash","-c","until timeout 1 bash -c 'cat < /dev/null > /dev/tcp/$RABBITMQ_HOST/$RABBITMQ_PORT'; do echo waiting; sleep 2; done;"]
      containers:
        - name: "fr-collector2"
          image: gcr.io/flight-globe/fr-collector2
          imagePullPolicy: Always
          env:
            - name: REDIS_ADDRESS
              value: redis-master
            - name: REDIS_PORT
              value: "6379"
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
          livenessProbe:
            exec:
             command:
               - /var/flightglobe/liveness.sh
            initialDelaySeconds: 30
            periodSeconds: 35
            failureThreshold: 1
          readinessProbe:
            exec:
              command:
                - /var/flightglobe/readiness.sh
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 1
