apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "fr-collector-deployment"
  labels:
    app: "fr-collector"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "fr-collector"
  template:
    metadata:
      labels:
        app: "fr-collector"
    spec:
      containers:
      - name: "fr-collector"
        image: gcr.io/flight-globe/fr-collector
        imagePullPolicy: Always
        env:
        - name: REDIS_ADDRESS
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PUB_CHANNEL
          value: new_data
        - name: REDIS_DATA_KEY
          value: flight_positions