apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  name: "fr-db-persistor"
  labels:
    app: fr-db-persistor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fr-db-persistor
  template:
    metadata:
      labels:
        app: fr-db-persistor
    spec:
      containers:
      - name: fr-db-persistor
        image: gcr.io/flight-globe/fr-db-persistor
        imagePullPolicy: Always
        env:
        - name: REDIS_ADDRESS
          value: redis-service
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_SUB_CHANNEL
          value: new_data
        - name: PIPELINEDB_USERNAME
          value: pipeline
        - name: PIPELINEDB_PASSWORD
          value: pipeline
        - name: PIPELINEDB_DBNAME
          value: pipeline
        - name: PIPELINEDB_HOST
          value: pipelinedb