apiVersion: apps/v1
kind: "Deployment"
metadata:
   name: "fg-redis-persistor"
   labels:
      app: redis-point-persistor
spec:
   replicas: 1
   selector:
      matchLabels:
         app: redis-point-persistor
   template:
      metadata:
         labels:
            app: redis-point-persistor
      spec:
         containers:
            - name: fg-redis-persistor
              image: gcr.io/flight-globe/fg-redis-persistor
              imagePullPolicy: Always
              env:
                 - name: REDIS_ADDRESS
                   value: redis-service
                 - name: REDIS_PORT
                   value: "6379"
                 - name: REDIS_SUB_CHANNEL
                   value: positions_raw
                 - name: REDIS_PUB_CHANNEL
                   value: positions_clean
                 - name: NATS_ADDRESS
                   value: nats-service
