version: "2"
services:
   redis:
      image: redis
      ports:
         - "6379:6379"
   rabbitmq:
      image: rabbitmq:3.8-management
      ports:
         - "5672:5672"
         - "15672:15672"
      environment:
         RABBITMQ_DEFAULT_USER: "user"
         RABBITMQ_DEFAULT_PASS: "secretpassword"
   deepstream:
      image: deepstream-server
      ports:
         - "6020:6020"
      links:
         - redis
      depends_on:
         - redis
      environment:
         REDIS_HOST: redis
         REDIS_PORT: 6379
   deepstream-pusher:
      image: deepstream-pusher
      links:
         - redis
         - deepstream
      depends_on:
         - redis
         - deepstream
      environment:
         REDIS_HOST: redis
         REDIS_PORT: 6379
         DEEPSTREAM_HOST: deepstream
         DEEPSTREAM_PORT: 6020
   fr-collector2:
      image: fr-collector2
      links:
         - redis
         - rabbitmq
      depends_on:
         - redis
         - rabbitmq
      environment:
         REDIS_ADDRESS: redis
         REDIS_PORT: 6379
         RABBITMQ_HOST: rabbitmq
         RABBITMQ_PORT: 5672
   fg-redis-persistor:
      image: fg-redis-persistor
      links:
         - redis
         - rabbitmq
      depends_on:
         - redis
         - rabbitmq
      environment:
         REDIS_ADDRESS: redis
         REDIS_PORT: 6379
         RABBITMQ_HOST: rabbitmq
         RABBITMQ_PORT: 5672
