version: '2'
services:
  web:
    build: .
    ports:
     - "8080:80"
     - "443:443"
  db:
    image: postgres
    command: postgres -B 1GB -d 2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: flightglobe
      POSTGRES_USER: flightglobe

