version: '2'
services:
  web:
    build: .
    ports:
     - "8080:80"
     - "443:443"
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: flightglobe
      POSTGRES_USER: flightglobe

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080