version: '2'
services:
  redis:
    image: redislabs/rejson
    ports:
      -  "6379:6379"
  benthos:
    image: jeffail/benthos
    ports:
      -  "4195:4195"
    links:
      - redis
    environment:
      INPUT_TYPE: redis_pubsub
      INPUT_REDIS_PUBSUB_URL: tcp://redis:6379
      INPUT_REDIS_PUBSUB_CHANNELS: new_data
      OUTPUT_TYPE: redis_pubsub
      OUTPUT_REDIS_PUBSUB_URL: tcp://redis:6379
      OUTPUT_REDIS_PUBSUB_CHANNEL: persist_data
  db:
    image: pipelinedb/pipelinedb
    ports:
      - 5432:5432
  fr-collector:
    image: gcr.io/flight-globe/fr-collector
    links:
    - redis
    depends_on:
    - fr-redis-persistor
    environment:
      REDIS_URL: redis:6379
      REDIS_PUB_CHANNEL: new_data
      REDIS_DATA_KEY: flight_positions
  fr-redis-persistor:
    image: gcr.io/flight-globe/fr-redis-persistor
    links:
    - redis
    environment:
      REDIS_ADDRESS: redis
      REDIS_PORT: 6379
      REDIS_SUB_CHANNEL: new_data
      REDIS_DATA_KEY: flight_positions
  server:
    image: gcr.io/flight-globe/server
    links:
    - redis
    ports:
      - 5000:8080
    environment:
      REDIS_URL: redis:6379
      REDIS_DATA_KEY: flight_positions
#  static:
#    image: gcr.io/flight-globe/static
#    ports:
#    - 3000:80
#  web:
#    build: .
#    ports:
#     - "8080:80"
#     - "443:443"
