version: "2"
services:
   redis:
      image: redis
      ports:
         - "6379:6379"
   rabbitmq:
      image: rabbitmq:3.8-management
      ports:
         - "5672:5672"
         - "15672:15672"
   deepstream:
      image: deepstream-server
      ports:
         - "6020:6020"
      links:
         - redis
      depends_on:
        - redis
      environment:
         REDIS_HOST: redis
         REDIS_PORT: 6379
   deepstream-pusher:
      image: deepstream-pusher
      links:
         - redis
         - deepstream
      depends_on:
         - redis
         - deepstream
      environment:
         REDIS_HOST: redis
         REDIS_PORT: 6379
         DEEPSTREAM_HOST: deepstream
         DEEPSTREAM_PORT: 6020
   benthos:
      image: jeffail/benthos
      ports:
         - "4195:4195"
      links:
         - redis
      environment:
         INPUT_TYPE: redis_pubsub
         INPUT_REDIS_PUBSUB_URL: tcp://redis:6379
         INPUT_REDIS_PUBSUB_CHANNELS: new_data
         OUTPUT_TYPE: redis_pubsub
         OUTPUT_REDIS_PUBSUB_URL: tcp://redis:6379
         OUTPUT_REDIS_PUBSUB_CHANNEL: persist_data
   db:
      image: pipelinedb/pipelinedb
      ports:
         - 5432:5432
   fr-collector:
      image: fr-collector
      links:
         - redis
      depends_on:
         - redis-point-persistor
      environment:
         REDIS_ADDRESS: redis
         REDIS_PORT: 6379
         REDIS_PUB_CHANNEL: new_data
         REDIS_DATA_KEY: flight_positions
   redis-point-persistor:
      image: fg-redis-persistor
      links:
         - redis
      environment:
         REDIS_ADDRESS: redis
         REDIS_PORT: 6379
         REDIS_SUB_CHANNEL: new_data
         REDIS_DATA_KEY: flight_positions
   fg-server:
      image: fg-server
      links:
         - redis
      ports:
         - 5000:8080
      environment:
         REDIS_ADDRESS: redis
         REDIS_PORT: 6379
         REDIS_DATA_KEY: flight_positions
#  static:
#    image: gcr.io/flight-globe/static
#    ports:
#    - 3000:80
#  web:
#    build: .
#    ports:
#     - "8080:80"
#     - "443:443"
