---
- name: Create Flightglobe group
  group:
    name: flightglobe
    state: present

- name: Setup Flightglobe user
  user:
    name: flightglobe
    group: flightglobe

- name: Setup Flightglobe database user
  become: true
  become_user: postgres
  postgresql_user:
    name: flightglobe
    password: flightglobe

- name: Create Flightglobe database
  become: true
  become_user: postgres
  postgresql_db:
    name: flightglobe
    owner: flightglobe

- name: Add hstore extension to Flightglobe database
  become: true
  become_user: postgres
  postgresql_ext:
    name: hstore
    db: flightglobe

- name: Create app directory
  file:
    path: /opt/flightglobe/
    state: directory
    owner: flightglobe
    group: flightglobe
    mode: 0755

- name: Copy Flightglobe collector
  copy:
    src: "{{inventory_dir}}/dataserver/cmd/collector/main"
    dest: /opt/flightglobe/collector
    owner: flightglobe
    group: flightglobe
    mode: 0700

- name: Copy Flightglobe sender
  copy:
    src: "{{inventory_dir}}/dataserver/cmd/sender/main"
    dest: /opt/flightglobe/sender
    owner: flightglobe
    group: flightglobe
    mode: 0700

- name: Copy Flightglobe SQL
  copy:
    src: "{{inventory_dir}}/database/schema.sql"
    dest: /opt/flightglobe/schema.sql
    owner: flightglobe
    group: flightglobe
    mode: 0700

#- name: Execute sql script
#  shell: "PGPASSWORD=flightglobe psql -h localhost -U flightglobe < /opt/flightglobe/schema.sql"

- name: Copy Flightglobe web app
  notify:
    - reload nginx
  tags:
    - current
  synchronize:
    src: "{{inventory_dir}}/client-build/"
    dest: /opt/flightglobe/static/
    checksum: yes

- name: Ensure Flightglobe web app group
  notify:
    - reload nginx
  tags:
    - current
  file:
    path: /opt/flightglobe/static
    owner: flightglobe
    recurse: yes
    mode: 0755

- name: Copy Flightglobe Nginx/Nchan configuration
  notify:
    - reload nginx
  tags:
    - current
  copy:
    src: "{{inventory_dir}}/dataserver/nginx/flightglobe.conf"
    dest: /etc/nginx/conf.d

- name: Add Nginx user to Flightglobe group
  tags:
    - current
  user:
    name: www-data
    groups: flightglobe
    append: yes