---
- name: Install Nginx-Nchan package
  apt:
    state: latest
    name: libnginx-mod-nchan
    cache_valid_time: 3600

- name: Install Nginx package
  apt:
    state: latest
    name: nginx
    cache_valid_time: 3600

- name: enable Nginx service
  service:
    name: nginx
    state: started
    enabled: yes

- name: Ensure Nginx default site is disabled
  notify:
  - reload nginx
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
